### ISSUE TITLE
need CoAP data on Qt

### ISSUE THREAD

**Issue by shantanoo-desai** [romixlab/qcoap#1]
Hello.
I am looking for a CoAP implemention on Qt. I have managed to get some data from CoAP server onto my Linux Gnome terminal and it is in JSON format. the value of the sensor keeps posting on gnome terminal through a CON reply which is running by making a example on SMCP 
I would like to access this data into Qt to make a simple GUI. 

Any help would be appreciated. 
for further details https://github.com/shantanoo-desai/coap-wsn

Thanks
shan

**Comment by romixlab** [comment]
Hello!
I'm now working on this, in a week or two the functionality you need will be there.
Also you can easily launch smcpctl from Qt app and process json data with QJsonDocument or qjson library.

**Comment by shantanoo-desai** [comment]
Hi Thanks for the help. 
I just have a question writing or reading on gnome terminal is possible using Qprocess? or are there better alternatives for the same?

**Comment by romixlab** [comment]
You could link to their [smcp] library and use it directly, but there are little problem - process loop, so it must be done in another thread or by timer, both methods have pros and cons...
